import { createFileRoute } from "@tanstack/react-router";
import { useState, type ReactNode } from "react";
import { buildCalculatorSeo } from "@/components/SEO";
import {
  MathCalcPage,
  Field,
  TextInput,
  PrimaryButton,
  ResultBox,
  ErrorBox,
  CalcSection,
  CalcFAQ,
  RelatedLinks,
  FeatureList,
  GuideCards,
  FormulaBlock,
  FormulaWithLegend,
  type GuideCardItem,
} from "@/components/MathCalcPage";
import { StepsToggle } from "@/components/StepsToggle";
import type { Step } from "@/components/SolutionSteps";

export const Route = createFileRoute("/calculators/math/number-sequence-calculator")({
  head: () =>
    buildCalculatorSeo({
      name: "Number Sequence Calculator",
      title:
        "Number Sequence Calculator — Arithmetic & Geometric",
      metaDescription:
        "Compute arithmetic, geometric and Fibonacci sequences. Get the nth term, term list, sum of n terms, and a growth plot.",
      canonicalUrl: "/calculators/math/number-sequence-calculator",
      breadcrumbs: [
        { name: "Home", path: "/" },
        { name: "Math", path: "/calculators/math" },
        {
          name: "Number Sequence Calculator",
          path: "/calculators/math/number-sequence-calculator",
        },
      ],
      faqs: [
        {
          q: "What is the difference between a sequence and a series?",
          a: "A sequence is an ordered list of numbers generated by a rule — 2, 5, 8, 11, 14, … A series is the running total of that list — 2 + 5 + 8 + 11 + 14 + … So the sequence describes the pattern; the series is what you get when you add the terms up.",
        },
        {
          q: "Why do Fibonacci numbers grow so fast?",
          a: "Each Fibonacci number is the sum of the two before it, so once the terms are large the sequence roughly doubles at every step. More precisely, the ratio of consecutive terms approaches the golden ratio φ ≈ 1.618, which means Fibonacci grows exponentially — F₅₀ already exceeds twelve billion.",
        },
        {
          q: "Can I compute Fibonacci for very large n here?",
          a: "Yes. This calculator uses JavaScript BigInt for the Fibonacci tool, so terms with hundreds or thousands of digits stay exact. Standard doubles would lose precision beyond about F₇₈.",
        },
        {
          q: "Does the geometric series always add up to a finite number?",
          a: "Only when |r| < 1. If the ratio is smaller than 1 in absolute value each new term shrinks, and the infinite sum converges to a₁ / (1 − r). If |r| ≥ 1 the terms do not shrink and the sum grows without bound.",
        },
      ],
    }),
  component: NumberSequencePage,
});

// ---------------- Number formatting ----------------

function fmtNum(n: number): string {
  if (Object.is(n, -0)) n = 0;
  if (!Number.isFinite(n)) return n > 0 ? "∞" : "−∞";
  const r = Math.round(n * 1e10) / 1e10;
  return r.toString();
}

/** Truncate a bigint's decimal string for display when it is very long. */
function fmtBig(n: bigint, maxDigits = 40): string {
  const s = n.toString();
  if (s.length <= maxDigits) return s;
  return `${s.slice(0, maxDigits - 6)}…${s.slice(-3)}  (${s.length} digits)`;
}

// ---------------- Line plot (shared) ----------------

interface Point {
  index: number;
  value: number;
}

/**
 * Small SVG line + scatter plot of the first several terms.
 * Auto-scales the y axis so linear, exponential and Fibonacci growth
 * are all visible on the same component. Falls back to numbers on the
 * axis; when values dwarf each other (geometric / Fibonacci) the
 * caller can pass logY.
 */
function SequencePlot({
  points,
  label,
  logY = false,
}: {
  points: Point[];
  label: string;
  logY?: boolean;
}) {
  if (points.length < 2) return null;

  const W = 560;
  const H = 220;
  const padL = 48;
  const padR = 16;
  const padT = 14;
  const padB = 34;
  const plotW = W - padL - padR;
  const plotH = H - padT - padB;

  // Map values (optionally through log10 with an offset for non-positive inputs).
  const rawVals = points.map((p) => p.value);
  const useLog = logY && rawVals.every((v) => v > 0);
  const mapY = (v: number) =>
    useLog ? Math.log10(Math.max(v, Number.MIN_VALUE)) : v;

  const yVals = rawVals.map(mapY);
  const yMin = Math.min(...yVals);
  const yMax = Math.max(...yVals);
  const ySpan = yMax - yMin || 1;
  const yPad = ySpan * 0.08;
  const yLo = yMin - yPad;
  const yHi = yMax + yPad;

  const xMin = points[0].index;
  const xMax = points[points.length - 1].index;

  const xToPx = (i: number) =>
    padL + ((i - xMin) / Math.max(1, xMax - xMin)) * plotW;
  const yToPx = (v: number) =>
    padT + plotH - ((mapY(v) - yLo) / (yHi - yLo)) * plotH;

  const zeroY =
    !useLog && yLo < 0 && yHi > 0 ? yToPx(0) : null;

  const linePts = points
    .map((p) => `${xToPx(p.index).toFixed(1)},${yToPx(p.value).toFixed(1)}`)
    .join(" ");

  // Choose x-axis tick spacing so labels don't crowd.
  const xTickStep = Math.max(1, Math.ceil((xMax - xMin) / 8));
  const xTicks: number[] = [];
  for (let i = xMin; i <= xMax; i += xTickStep) xTicks.push(i);
  if (xTicks[xTicks.length - 1] !== xMax) xTicks.push(xMax);

  // Four y ticks across the range.
  const yTicks: number[] = [];
  for (let k = 0; k <= 4; k++) {
    const mappedTick = yLo + ((yHi - yLo) * k) / 4;
    const value = useLog ? Math.pow(10, mappedTick) : mappedTick;
    yTicks.push(value);
  }

  const formatYTick = (v: number) => {
    const abs = Math.abs(v);
    if (abs !== 0 && (abs < 0.01 || abs >= 1e6)) return v.toExponential(1);
    if (Number.isInteger(v)) return v.toString();
    return v.toPrecision(3);
  };

  return (
    <div className="mt-4 rounded-lg border border-border bg-card/50 p-3">
      <div className="mb-2 flex items-center justify-between text-xs text-muted-foreground">
        <span className="font-medium">{label}</span>
        {useLog && <span className="italic">y axis: log₁₀ scale</span>}
      </div>
      <svg
        viewBox={`0 0 ${W} ${H}`}
        className="h-auto w-full"
        role="img"
        aria-label={label}
      >
        {/* y grid + labels */}
        {yTicks.map((v, i) => {
          const y = padT + plotH - (i * plotH) / 4;
          return (
            <g key={`y${i}`}>
              <line
                x1={padL}
                x2={W - padR}
                y1={y}
                y2={y}
                stroke="currentColor"
                strokeOpacity={0.1}
              />
              <text
                x={padL - 6}
                y={y + 4}
                textAnchor="end"
                className="fill-muted-foreground"
                fontSize="10"
              >
                {formatYTick(v)}
              </text>
            </g>
          );
        })}

        {/* axes */}
        <line
          x1={padL}
          y1={padT}
          x2={padL}
          y2={H - padB}
          stroke="currentColor"
          strokeOpacity={0.5}
        />
        <line
          x1={padL}
          y1={H - padB}
          x2={W - padR}
          y2={H - padB}
          stroke="currentColor"
          strokeOpacity={0.5}
        />

        {/* zero line when values straddle zero */}
        {zeroY !== null && (
          <line
            x1={padL}
            x2={W - padR}
            y1={zeroY}
            y2={zeroY}
            stroke="currentColor"
            strokeOpacity={0.35}
            strokeDasharray="3 3"
          />
        )}

        {/* x ticks */}
        {xTicks.map((t) => (
          <g key={`x${t}`}>
            <line
              x1={xToPx(t)}
              x2={xToPx(t)}
              y1={H - padB}
              y2={H - padB + 4}
              stroke="currentColor"
              strokeOpacity={0.5}
            />
            <text
              x={xToPx(t)}
              y={H - padB + 16}
              textAnchor="middle"
              className="fill-muted-foreground"
              fontSize="10"
            >
              {t}
            </text>
          </g>
        ))}

        {/* the line itself */}
        <polyline
          points={linePts}
          fill="none"
          stroke="var(--color-primary)"
          strokeWidth={2}
        />

        {/* term dots */}
        {points.map((p) => (
          <circle
            key={p.index}
            cx={xToPx(p.index)}
            cy={yToPx(p.value)}
            r={3.5}
            fill="var(--color-primary)"
          />
        ))}

        {/* axis labels */}
        <text
          x={padL + plotW / 2}
          y={H - 4}
          textAnchor="middle"
          className="fill-muted-foreground"
          fontSize="10"
        >
          term index n
        </text>
        <text
          x={14}
          y={padT + plotH / 2}
          textAnchor="middle"
          className="fill-muted-foreground"
          fontSize="10"
          transform={`rotate(-90 14 ${padT + plotH / 2})`}
        >
          value aₙ
        </text>
      </svg>
    </div>
  );
}

// ---------------- Term list (shared) ----------------

function TermList({ items }: { items: string[] }) {
  return (
    <div className="mt-3 overflow-x-auto rounded-lg border border-border bg-card/30 p-3">
      <p className="font-serif italic text-sm leading-relaxed break-words">
        {items.join(", ")}
        {items.length > 0 && ", …"}
      </p>
    </div>
  );
}

// ============================================================
// 1. Arithmetic
// ============================================================

interface ArithmeticResult {
  a1: number;
  d: number;
  n: number;
  terms: number[];
  nth: number;
  sum: number;
  steps: Step[];
}

function computeArithmetic(
  a1: number,
  d: number,
  n: number,
): ArithmeticResult {
  const terms: number[] = [];
  const listMax = Math.min(n, 20);
  for (let i = 1; i <= listMax; i++) terms.push(a1 + (i - 1) * d);
  const nth = a1 + (n - 1) * d;
  const sum = (n / 2) * (2 * a1 + (n - 1) * d);

  const steps: Step[] = [
    {
      title: "Given",
      body: (
        <FormulaBlock>
          a₁ = {fmtNum(a1)}, d = {fmtNum(d)}, n = {n}
        </FormulaBlock>
      ),
    },
    {
      title: "Formula — arithmetic sequence",
      body: (
        <FormulaWithLegend
          formula={<>aₙ = a₁ + (n − 1)·d; &nbsp; Sₙ = n/2 · (2a₁ + (n − 1)·d)</>}
          legend={[
            { sym: "a₁", def: "first term" },
            { sym: "d", def: "common difference" },
            { sym: "n", def: "term index" },
          ]}
        />
      ),
    },
    {
      title: "Substitute — nth term",
      body: (
        <FormulaBlock>
          aₙ = {fmtNum(a1)} + ({n} − 1)·{fmtNum(d)} = {fmtNum(nth)}
        </FormulaBlock>
      ),
    },
    {
      title: "Substitute — sum",
      body: (
        <FormulaBlock>
          Sₙ = {n}/2 · (2·{fmtNum(a1)} + ({n} − 1)·{fmtNum(d)}) = {fmtNum(sum)}
        </FormulaBlock>
      ),
    },
    {
      title: "Answer",
      body: <FormulaBlock>aₙ = {fmtNum(nth)}, &nbsp; Sₙ = {fmtNum(sum)}</FormulaBlock>,
    },
  ];

  return { a1, d, n, terms, nth, sum, steps };
}

function ArithmeticTool() {
  const [a1, setA1] = useState("2");
  const [d, setD] = useState("5");
  const [n, setN] = useState("20");
  const [result, setResult] = useState<ArithmeticResult | null>(null);
  const [err, setErr] = useState<string | null>(null);

  const onCalc = () => {
    setErr(null);
    setResult(null);
    const A = Number(a1);
    const D = Number(d);
    const N = Number(n);
    if (!Number.isFinite(A) || !Number.isFinite(D))
      return setErr("First term and common difference must be numbers.");
    if (!Number.isInteger(N) || N < 1 || N > 5000)
      return setErr("n must be a positive integer up to 5000.");
    setResult(computeArithmetic(A, D, N));
  };

  const value: ReactNode = result ? (
    <span className="font-serif italic">
      a{result.n} = {fmtNum(result.nth)} &nbsp;·&nbsp; S{result.n} ={" "}
      {fmtNum(result.sum)}
    </span>
  ) : null;

  const plotPoints: Point[] = result
    ? result.terms
        .slice(0, Math.min(result.terms.length, 15))
        .map((v, i) => ({ index: i + 1, value: v }))
    : [];

  return (
    <section>
      <h2 className="mb-1 font-display text-xl font-semibold text-foreground">
        1. Arithmetic Sequence Calculator
      </h2>
      <p className="mb-1 text-sm text-muted-foreground">
        Definition: aₙ = a₁ + d·(n − 1)
      </p>
      <p className="mb-4 text-sm text-muted-foreground">
        Example: 1, 3, 5, 7, 9, 11, 13, …
      </p>
      <div className="space-y-4">
        <div className="grid gap-3 sm:grid-cols-3">
          <Field label="First term a₁">
            <TextInput
              value={a1}
              inputMode="decimal"
              onChange={(e) => setA1(e.target.value)}
            />
          </Field>
          <Field label="Common difference d">
            <TextInput
              value={d}
              inputMode="decimal"
              onChange={(e) => setD(e.target.value)}
            />
          </Field>
          <Field label="nth term to obtain">
            <TextInput
              value={n}
              inputMode="numeric"
              onChange={(e) => setN(e.target.value)}
            />
          </Field>
        </div>
        <PrimaryButton onClick={onCalc}>Calculate arithmetic sequence</PrimaryButton>
      </div>

      {err && <ErrorBox message={err} />}

      {result && (
        <>
          <ResultBox
            label={`Arithmetic sequence, first ${result.n} terms`}
            value={value}
            note={`Showing the first ${result.terms.length} of ${result.n} terms below.`}
          />
          <TermList items={result.terms.map((t) => fmtNum(t))} />
          <SequencePlot
            points={plotPoints}
            label="Arithmetic sequence — linear growth"
          />
          <StepsToggle steps={result.steps} />
        </>
      )}
    </section>
  );
}

// ============================================================
// 2. Geometric
// ============================================================

interface GeometricResult {
  a1: number;
  r: number;
  n: number;
  terms: number[];
  nth: number;
  sum: number;
  steps: Step[];
}

function computeGeometric(a1: number, r: number, n: number): GeometricResult {
  const terms: number[] = [];
  const listMax = Math.min(n, 20);
  for (let i = 1; i <= listMax; i++) terms.push(a1 * Math.pow(r, i - 1));
  const nth = a1 * Math.pow(r, n - 1);
  const sum =
    Math.abs(r - 1) < 1e-15
      ? a1 * n
      : (a1 * (1 - Math.pow(r, n))) / (1 - r);

  const steps: Step[] = [
    {
      title: "Given",
      body: (
        <FormulaBlock>
          a = {fmtNum(a1)}, r = {fmtNum(r)}, n = {n}
        </FormulaBlock>
      ),
    },
    {
      title: "Formula — geometric sequence",
      body: (
        <FormulaWithLegend
          formula={<>aₙ = a · rⁿ⁻¹; &nbsp; Sₙ = a · (1 − rⁿ) / (1 − r), r ≠ 1</>}
          legend={[
            { sym: "a", def: "first term" },
            { sym: "r", def: "common ratio" },
            { sym: "n", def: "term index" },
          ]}
        />
      ),
    },
    {
      title: "Substitute — nth term",
      body: (
        <FormulaBlock>
          aₙ = {fmtNum(a1)} · ({fmtNum(r)})^({n} − 1) = {fmtNum(nth)}
        </FormulaBlock>
      ),
    },
    {
      title: "Substitute — sum",
      body:
        Math.abs(r - 1) < 1e-15 ? (
          <FormulaBlock>
            r = 1 → Sₙ = n·a = {n} · {fmtNum(a1)} = {fmtNum(sum)}
          </FormulaBlock>
        ) : (
          <FormulaBlock>
            Sₙ = {fmtNum(a1)} · (1 − {fmtNum(Math.pow(r, n))}) / {fmtNum(1 - r)} = {fmtNum(sum)}
          </FormulaBlock>
        ),
    },
    {
      title: "Answer",
      body: <FormulaBlock>aₙ = {fmtNum(nth)}, &nbsp; Sₙ = {fmtNum(sum)}</FormulaBlock>,
    },
  ];

  return { a1, r, n, terms, nth, sum, steps };
}

function GeometricTool() {
  const [a1, setA1] = useState("2");
  const [r, setR] = useState("5");
  const [n, setN] = useState("12");
  const [result, setResult] = useState<GeometricResult | null>(null);
  const [err, setErr] = useState<string | null>(null);

  const onCalc = () => {
    setErr(null);
    setResult(null);
    const A = Number(a1);
    const R = Number(r);
    const N = Number(n);
    if (!Number.isFinite(A) || !Number.isFinite(R))
      return setErr("First term and common ratio must be numbers.");
    if (!Number.isInteger(N) || N < 1 || N > 1000)
      return setErr("n must be a positive integer up to 1000.");
    const res = computeGeometric(A, R, N);
    if (!Number.isFinite(res.nth) || !Number.isFinite(res.sum))
      return setErr(
        "The result overflowed regular floating-point range — try a smaller n or a ratio closer to 1.",
      );
    setResult(res);
  };

  const value: ReactNode = result ? (
    <span className="font-serif italic">
      a{result.n} = {fmtNum(result.nth)} &nbsp;·&nbsp; S{result.n} ={" "}
      {fmtNum(result.sum)}
    </span>
  ) : null;

  // Use log scale when terms span more than ~4 orders of magnitude
  // AND all terms have the same sign (log is undefined otherwise).
  const useLog = (() => {
    if (!result) return false;
    const abs = result.terms.map((t) => Math.abs(t)).filter((v) => v > 0);
    if (abs.length < 2) return false;
    const allPositive = result.terms.every((t) => t > 0);
    return allPositive && Math.max(...abs) / Math.min(...abs) > 1e4;
  })();

  const plotPoints: Point[] = result
    ? result.terms
        .slice(0, Math.min(result.terms.length, 12))
        .map((v, i) => ({ index: i + 1, value: v }))
    : [];

  return (
    <section>
      <h2 className="mb-1 font-display text-xl font-semibold text-foreground">
        2. Geometric Sequence Calculator
      </h2>
      <p className="mb-1 text-sm text-muted-foreground">
        Definition: aₙ = a · r^(n − 1)
      </p>
      <p className="mb-4 text-sm text-muted-foreground">
        Example: 1, 2, 4, 8, 16, 32, 64, 128, …
      </p>
      <div className="space-y-4">
        <div className="grid gap-3 sm:grid-cols-3">
          <Field label="First term a">
            <TextInput
              value={a1}
              inputMode="decimal"
              onChange={(e) => setA1(e.target.value)}
            />
          </Field>
          <Field label="Common ratio r">
            <TextInput
              value={r}
              inputMode="decimal"
              onChange={(e) => setR(e.target.value)}
            />
          </Field>
          <Field label="nth term to obtain">
            <TextInput
              value={n}
              inputMode="numeric"
              onChange={(e) => setN(e.target.value)}
            />
          </Field>
        </div>
        <PrimaryButton onClick={onCalc}>Calculate geometric sequence</PrimaryButton>
      </div>

      {err && <ErrorBox message={err} />}

      {result && (
        <>
          <ResultBox
            label={`Geometric sequence, first ${result.n} terms`}
            value={value}
            note={
              Math.abs(result.r) < 1
                ? `|r| < 1, so the infinite sum converges to ${fmtNum(result.a1 / (1 - result.r))}.`
                : Math.abs(result.r) === 1
                  ? "|r| = 1 — the terms do not shrink, so no finite sum to infinity."
                  : "|r| > 1 — the terms grow, so the infinite sum diverges."
            }
          />
          <TermList items={result.terms.map((t) => fmtNum(t))} />
          <SequencePlot
            points={plotPoints}
            label={`Geometric sequence — ${Math.abs(result.r) > 1 ? "exponential growth" : Math.abs(result.r) < 1 ? "exponential decay" : "constant"}`}
            logY={useLog}
          />
          <StepsToggle steps={result.steps} />
        </>
      )}
    </section>
  );
}

// ============================================================
// 3. Fibonacci (BigInt)
// ============================================================

interface FibResult {
  n: number;
  terms: bigint[]; // F₀ .. F_min(n,20)
  nth: bigint; // Fₙ
  steps: Step[];
}

/**
 * Fast doubling — computes (F_k, F_{k+1}) in O(log k) BigInt operations,
 * so even n in the thousands stays instant.
 */
function fibPair(k: number): [bigint, bigint] {
  if (k === 0) return [0n, 1n];
  const [a, b] = fibPair(Math.floor(k / 2));
  const c = a * (2n * b - a);
  const d = a * a + b * b;
  return k % 2 === 0 ? [c, d] : [d, c + d];
}

function computeFibonacci(n: number): FibResult {
  const listMax = Math.min(n, 20);
  const terms: bigint[] = [];
  let a = 0n;
  let b = 1n;
  for (let i = 0; i <= listMax; i++) {
    terms.push(a);
    const next = a + b;
    a = b;
    b = next;
  }
  const nth = n <= listMax ? terms[n] : fibPair(n)[0];

  const steps: Step[] = [
    {
      title: "Given",
      body: <FormulaBlock>n = {n}</FormulaBlock>,
    },
    {
      title: "Formula — Fibonacci recurrence",
      body: (
        <FormulaWithLegend
          formula={<>F₀ = 0, &nbsp; F₁ = 1, &nbsp; Fₙ = Fₙ₋₁ + Fₙ₋₂ for n ≥ 2</>}
          legend={[
            { sym: "Fₙ", def: "nth Fibonacci number" },
            { sym: "Fₙ₋₁, Fₙ₋₂", def: "the two preceding terms" },
          ]}
        />
      ),
    },
    {
      title: `Substitute — build up to F${Math.min(n, 8)}`,
      body: (
        <FormulaBlock>
          F₀ = 0, F₁ = 1, F₂ = 1, F₃ = 2, F₄ = 3, F₅ = 5, F₆ = 8, F₇ = 13, F₈ = 21…
        </FormulaBlock>
      ),
    },
    {
      title: `Answer — F${n}`,
      body: <FormulaBlock>{fmtBig(nth)}</FormulaBlock>,
    },
  ];

  return { n, terms, nth, steps };
}

function FibonacciTool() {
  const [n, setN] = useState("10");
  const [result, setResult] = useState<FibResult | null>(null);
  const [err, setErr] = useState<string | null>(null);

  const onCalc = () => {
    setErr(null);
    setResult(null);
    const N = Number(n);
    if (!Number.isInteger(N) || N < 0 || N > 10000)
      return setErr("n must be a whole number between 0 and 10 000.");
    setResult(computeFibonacci(N));
  };

  const value: ReactNode = result ? (
    <span className="font-serif italic break-words">
      F{result.n} = {fmtBig(result.nth)}
    </span>
  ) : null;

  // Use plot on numeric-safe subset (avoid infinity in the SVG).
  const plotPoints: Point[] = result
    ? result.terms
        .slice(0, Math.min(result.terms.length, 15))
        .map((v, i) => ({ index: i, value: Number(v) }))
        .filter((p) => Number.isFinite(p.value))
    : [];

  const useLog =
    plotPoints.length >= 4 &&
    plotPoints.every((p) => p.value > 0) &&
    plotPoints[plotPoints.length - 1].value /
      Math.max(plotPoints[1].value, 1) >
      1e3;

  return (
    <section>
      <h2 className="mb-1 font-display text-xl font-semibold text-foreground">
        3. Fibonacci Sequence Calculator
      </h2>
      <p className="mb-1 text-sm text-muted-foreground">
        Definition: F₀ = 0, F₁ = 1, Fₙ = Fₙ₋₁ + Fₙ₋₂
      </p>
      <p className="mb-4 text-sm text-muted-foreground">
        Example: 0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, …
      </p>
      <div className="space-y-4">
        <Field label="nth term to obtain">
          <TextInput
            value={n}
            inputMode="numeric"
            onChange={(e) => setN(e.target.value)}
          />
        </Field>
        <PrimaryButton onClick={onCalc}>Calculate Fibonacci</PrimaryButton>
      </div>

      {err && <ErrorBox message={err} />}

      {result && (
        <>
          <ResultBox
            label={`Fibonacci — F${result.n}`}
            value={value}
            note={
              result.terms.length <= result.n
                ? `Showing the first ${result.terms.length} terms below; Fₙ itself is computed exactly with BigInt.`
                : `Full sequence up to F${result.n} below.`
            }
          />
          <TermList items={result.terms.map((t) => t.toString())} />
          <SequencePlot
            points={plotPoints}
            label="Fibonacci sequence — nearly exponential growth"
            logY={useLog}
          />
          <StepsToggle steps={result.steps} />
        </>
      )}
    </section>
  );
}

// ============================================================
// Page shell
// ============================================================

/* ---------------- Guide diagrams ---------------- */

function MiniPlot({
  values,
  label,
  logScale = false,
}: {
  values: number[];
  label: string;
  logScale?: boolean;
}) {
  const w = 320, h = 140, padL = 30, padR = 15, padT = 15, padB = 25;
  const xs = values.map((_, i) => i);
  const ys = logScale ? values.map((v) => Math.log10(Math.max(v, 1))) : values;
  const minY = Math.min(...ys, 0);
  const maxY = Math.max(...ys, 1);
  const spanY = maxY - minY || 1;
  const xToPx = (i: number) => padL + (i / Math.max(xs.length - 1, 1)) * (w - padL - padR);
  const yToPx = (v: number) => h - padB - ((v - minY) / spanY) * (h - padT - padB);
  const path = ys.map((v, i) => `${i === 0 ? "M" : "L"} ${xToPx(i).toFixed(1)} ${yToPx(v).toFixed(1)}`).join(" ");
  return (
    <svg viewBox={`0 0 ${w} ${h}`} className="w-full" role="img" aria-label={label}>
      <line x1={padL} y1={h - padB} x2={w - padR} y2={h - padB} stroke="var(--color-border)" />
      <line x1={padL} y1={padT} x2={padL} y2={h - padB} stroke="var(--color-border)" />
      <path d={path} fill="none" stroke="var(--color-primary)" strokeWidth={2} />
      {values.map((_, i) => (
        <circle key={i} cx={xToPx(i)} cy={yToPx(ys[i])} r={3} fill="var(--color-primary)" />
      ))}
      <text x={w / 2} y={h - 6} textAnchor="middle" fontSize={10} fill="var(--color-muted-foreground)">n →</text>
      {logScale && (
        <text x={w - padR} y={padT + 10} textAnchor="end" fontSize={9} fill="var(--color-muted-foreground)">
          log scale
        </text>
      )}
    </svg>
  );
}

/* ---------------- Guide ---------------- */

const SEQ_GUIDE: GuideCardItem[] = [
  {
    key: "arithmetic",
    title: "Arithmetic sequence — constant difference",
    explain:
      "An arithmetic sequence adds the same number every step. That constant is the common difference d. Because each jump is identical in size, the terms lie on a straight line — growth (or decline, if d is negative) is linear.",
    formula: (
      <>
        aₙ = a₁ + (n − 1)·d
        <br />
        Sₙ = n/2 · (a₁ + aₙ)
      </>
    ),
    legend: [
      { sym: "a₁", def: "first term" },
      { sym: "d", def: "common difference" },
      { sym: "n", def: "term index (1-based)" },
      { sym: "Sₙ", def: "sum of the first n terms" },
    ],
    diagram: <MiniPlot values={[2, 7, 12, 17, 22]} label="Arithmetic growth is a straight line" />,
    example: {
      given: "a₁ = 2, d = 5, n = 5",
      substitute: "a₅ = 2 + 4·5, S₅ = 5/2·(2 + 22)",
      answer: "a₅ = 22, S₅ = 60",
    },
  },
  {
    key: "geometric",
    title: "Geometric sequence — constant ratio",
    explain:
      "A geometric sequence multiplies by the same number every step. That constant is the common ratio r. Because each term is scaled by a fixed factor, growth is exponential — or, when |r| < 1, an exponential decay towards zero. The infinite sum only converges when |r| < 1.",
    formula: (
      <>
        aₙ = a · r^(n − 1)
        <br />
        Sₙ = a · (1 − rⁿ) / (1 − r), &nbsp; r ≠ 1
      </>
    ),
    legend: [
      { sym: "a", def: "first term" },
      { sym: "r", def: "common ratio" },
      { sym: "n", def: "term index" },
      { sym: "S∞", def: "= a / (1 − r) when |r| < 1" },
    ],
    diagram: <MiniPlot values={[2, 10, 50, 250, 1250]} label="Geometric growth (log scale)" logScale />,
    example: {
      given: "a = 2, r = 5, n = 4",
      substitute: "a₄ = 2·5³, S₄ = 2·(1 − 5⁴)/(1 − 5)",
      answer: "a₄ = 250, S₄ = 312",
    },
  },
  {
    key: "fibonacci",
    title: "Fibonacci sequence — sum of the two before",
    explain:
      "Fibonacci is defined by the simplest possible recurrence: each term is the sum of the two before it. Consecutive ratios Fₙ/Fₙ₋₁ approach the golden ratio φ ≈ 1.618…, which is why Fibonacci grows roughly like φⁿ — much slower than doubling, but still exponential. The sequence appears in phyllotaxis, honeybee family trees and combinatorial counts.",
    formula: <>Fₙ = Fₙ₋₁ + Fₙ₋₂, with F₀ = 0, F₁ = 1</>,
    legend: [
      { sym: "Fₙ", def: "nth Fibonacci number" },
      { sym: "φ", def: "golden ratio ≈ 1.618" },
    ],
    diagram: <MiniPlot values={[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]} label="Fibonacci growth" />,
    example: {
      given: "F₀ = 0, F₁ = 1, up to F₉",
      substitute: "0, 1, 1, 2, 3, 5, 8, 13, 21, 34",
      answer: "F₉ = 34",
    },
  },
];

function NumberSequencePage() {
  return (
    <MathCalcPage
      name="Number Sequence Calculator"
      tagline="Arithmetic, geometric and Fibonacci — all on one page. Enter the first term(s) and how many terms you want, and see the nth value, the running sum, the full term list and a small plot of how the sequence grows."
      extras={
        <>

          <CalcSection title="What is a number sequence?">
            <p>
              A sequence is an ordered list of numbers that follows a rule.
              Each entry is a <strong>term</strong>, and the position of a
              term is its <strong>index</strong>, usually written with a
              subscript: a₁ is the first term, a₂ the second, and so on.
            </p>
            <p>
              A rule can be given as a formula in n (like{" "}
              <span className="font-serif italic">aₙ = 3n − 1</span>) or as a
              recurrence that says how each term depends on the previous
              ones (like Fibonacci's{" "}
              <span className="font-serif italic">Fₙ = Fₙ₋₁ + Fₙ₋₂</span>). This
              page covers the three sequence families you meet most often
              at school and in day-to-day problems.
            </p>
          </CalcSection>

          <CalcSection title="Sequences, one type at a time">
            <p className="text-sm text-muted-foreground">
              Each card has a plain-English definition, the formulas for the
              nth term and running sum (with every symbol spelled out), a small
              growth diagram, and a worked example.
            </p>
            <GuideCards items={SEQ_GUIDE} />
          </CalcSection>

          <CalcSection title="Features of this calculator">
            <FeatureList
              items={[
                "Three distinct sub-tools on one page — no need to switch calculators for arithmetic, geometric or Fibonacci",
                "Renders the actual list of terms, not just the nth value",
                "Auto-scaled line plot for every sub-tool so linear, exponential and Fibonacci-style growth are visible at a glance",
                "Geometric mode switches to a log-scale y-axis when the terms span many orders of magnitude",
                "Fibonacci computed with BigInt and fast doubling — accurate for n in the thousands, not capped at ~F₇₈ like floating point",
                "Handles negative common difference / ratio, including alternating signs",
                "Step-by-step working using the standard closed-form formulas",
              ]}
            />
          </CalcSection>


          
<CalcSection title="Frequently asked questions">
            <CalcFAQ
              items={[
                {
                  q: "What is the difference between a sequence and a series?",
                  a: (
                    <p>
                      A sequence is the ordered list itself (2, 5, 8, 11,
                      …). A series is what you get when you add the
                      terms up (2 + 5 + 8 + 11 + …). This calculator
                      always reports both: the list and the running
                      total Sₙ.
                    </p>
                  ),
                },
                {
                  q: "Why do Fibonacci numbers grow so fast?",
                  a: (
                    <p>
                      Each new term adds the previous one, so once
                      you're past the first few values the sequence is
                      roughly multiplying by the golden ratio φ ≈ 1.618
                      at every step. That is exponential growth — F₃₀ is
                      already 832 040, and F₁₀₀ has 21 digits.
                    </p>
                  ),
                },
                {
                  q: "Can the common difference or ratio be negative?",
                  a: (
                    <p>
                      Yes. A negative common difference makes an
                      arithmetic sequence decrease (10, 7, 4, 1, −2, …).
                      A negative common ratio makes a geometric sequence
                      alternate signs (3, −6, 12, −24, …). Both are
                      handled here, including in the plot.
                    </p>
                  ),
                },
                {
                  q: "Do sequences start at n = 0 or n = 1?",
                  a: (
                    <p>
                      Both conventions are common. Arithmetic and
                      geometric tools here start at{" "}
                      <span className="font-serif italic">a₁</span>. The
                      Fibonacci tool uses the standard{" "}
                      <span className="font-serif italic">F₀ = 0</span>,{" "}
                      <span className="font-serif italic">F₁ = 1</span> so the
                      indexing lines up with what most textbooks and
                      OEIS use.
                    </p>
                  ),
                },
              ]}
            />
          </CalcSection>

          <CalcSection title="Related calculators">
            <RelatedLinks
              links={[
                {
                  to: "/calculators/math/sequence-calculator",
                  label: "Sequence & Series Calculator",
                },
                {
                  to: "/calculators/math/exponent-calculator",
                  label: "Exponent Calculator",
                },
              ]}
            />
          </CalcSection>
        </>
      }
    >
      <div className="space-y-10">
        <ArithmeticTool />
        <div className="h-px bg-border/60" />
        <GeometricTool />
        <div className="h-px bg-border/60" />
        <FibonacciTool />
      </div>
    </MathCalcPage>
  );
}
